#! /bin/csh
# set verbose
# create a backup directory
set w=`whoami`.pmk
set OLD=/tmp/$w/OLD
if ( -d $OLD ) then
else
   mkdir -p $OLD
   echo "$OLD directory created"
endif
# save some files into the backup directory
echo "Saving old files into $OLD directory"
mv minitoc.sty mtcoff.sty mtcmess.sty minitoc.ist minitoc-fr.dtx minitoc-fr.ist minitoc.pre $OLD
mv minitoc.lan minitoc-fr.lan $OLD
mv boldsc.sty mypatches.sty franc.sty frbib.sty frnew.sty $OLD
mv mtcpatchmem.sty $OLD
mv *.mld $OLD
mv *.mlo $OLD
mv mtc-add.bib $OLD
foreach i ( \
   mtc-2c mtc-2nd mtc-3co mtc-add mtc-ads mtc-amm mtc-apx mtc-art \
   mtc-bk mtc-bo mtc-ch0 mtc-cri mtc-fko mtc-fo1 mtc-fo2 mtc-gap \
   mtc-hi1 mtc-hi2 mtc-hia mtc-hir mtc-hop mtc-liv \
   mtc-mem mtc-mm1 mtc-mu mtc-nom mtc-ocf mtc-ofs mtc-sbf mtc-scr mtc-syn \
   mtc-tbi mtc-tlc mtc-tlo mtc-tsf mtc-vti \
)
   foreach j ( tex pdf )
   mv $i.$j $OLD
   end
end
echo 'Creating the package... you can sip a cappuccino'
# create the package from minitoc.ins and minitoc.dtx
latex minitoc.ins
cat mtc-add.bib | grep -v '^%%' > addbib;mv addbib mtc-add.bib
# save the log file of this phase
cp minitoc.log minitoc.log1
# create the documentation (DVI): 4 latex runs, with index and biblio
if ( -f minitoc.dtx ) then
if ( -f minitoc.maf ) then
   cat minitoc.maf | xargs -i -t \rm {}
endif
echo 'Creating the english documentation...'
touch minitoc.idx minitoc.ind
pdflatex minitoc.dtx
grep -v  '\\ \[]\|'  minitoc.idx | grep -v '|main}{1}$' | grep -v '\! =\\verb\!\*+\!\\\! +' > minitoc.idx1; mv minitoc.idx1 minitoc.idx
sed -e's/:>/=/' < minitoc.idx > minitoc.idx1; mv minitoc.idx1 minitoc.idx
bibtex minitoc
makeindex -s minitoc.ist -o minitoc.ind minitoc.idx
mv minitoc.ilg minitoc.ilg1
#
pdflatex minitoc.dtx
grep -v  '\\ \[]\|'  minitoc.idx | grep -v '|main}{1}$' | grep -v '\! =\\verb\!\*+\!\\\! +' > minitoc.idx1; mv minitoc.idx1 minitoc.idx
sed -e's/:>/=/' < minitoc.idx > minitoc.idx1; mv minitoc.idx1 minitoc.idx
makeindex -s minitoc.ist -o minitoc.ind minitoc.idx
mv minitoc.ilg minitoc.ilg1
#
pdflatex minitoc.dtx
grep -v  '\\ \[]\|'  minitoc.idx | grep -v '|main}{1}$' | grep -v '\! =\\verb\!\*+\!\\\! +' > minitoc.idx1; mv minitoc.idx1 minitoc.idx
sed -e's/:>/=/' < minitoc.idx > minitoc.idx1; mv minitoc.idx1 minitoc.idx
makeindex -s minitoc.ist -o minitoc.ind minitoc.idx
mv minitoc.ilg minitoc.ilg1
#
pdflatex minitoc.dtx
grep -v  '\\ \[]\|'  minitoc.idx | grep -v '|main}{1}$' | grep -v '\! =\\verb\!\*+\!\\\! +' > minitoc.idx1; mv minitoc.idx1 minitoc.idx
sed -e's/:>/=/' < minitoc.idx > minitoc.idx1; mv minitoc.idx1 minitoc.idx
endif
# french documentation
if ( -f minitoc-fr.dtx ) then
if ( -f minitoc-fr.maf ) then
   cat minitoc-fr.maf | xargs -i -t \rm {}
endif
echo 'Creating the french documentation...'
touch minitoc-fr.idx minitoc-fr.ind
# create the french documentation (PDF): 4 pdflatex runs, with index and biblio
pdflatex minitoc-fr.dtx
grep -v  '\\ \[]\|'  minitoc-fr.idx | grep -v '|main}{1}$' | grep -v '\! =\\verb\!\*+\!\\\! +' > minitoc-fr.idx1; mv minitoc-fr.idx1 minitoc-fr.idx
sed -e's/:>/=/' < minitoc-fr.idx > minitoc-fr.idx1; mv minitoc-fr.idx1 minitoc-fr.idx
bibtex minitoc-fr
makeindex -s minitoc-fr.ist -o minitoc-fr.ind minitoc-fr.idx
mv minitoc-fr.ilg minitoc-fr.ilg1
#
pdflatex minitoc-fr.dtx
grep -v  '\\ \[]\|'  minitoc-fr.idx | grep -v '|main}{1}$' | grep -v '\! =\\verb\!\*+\!\\\! +' > minitoc-fr.idx1; mv minitoc-fr.idx1 minitoc-fr.idx
sed -e's/:>/=/' < minitoc-fr.idx > minitoc-fr.idx1; mv minitoc-fr.idx1 minitoc-fr.idx
makeindex -s minitoc-fr.ist -o minitoc-fr.ind minitoc-fr.idx
mv minitoc-fr.ilg minitoc-fr.ilg1
#
pdflatex minitoc-fr.dtx
grep -v  '\\ \[]\|'  minitoc-fr.idx | grep -v '|main}{1}$' | grep -v '\! =\\verb\!\*+\!\\\! +' > minitoc-fr.idx1; mv minitoc-fr.idx1 minitoc-fr.idx
sed -e's/:>/=/' < minitoc-fr.idx > minitoc-fr.idx1; mv minitoc-fr.idx1 minitoc-fr.idx
makeindex -s minitoc-fr.ist -o minitoc-fr.ind minitoc-fr.idx
mv minitoc-fr.ilg minitoc-fr.ilg1
#
pdflatex minitoc-fr.dtx
grep -v  '\\ \[]\|'  minitoc-fr.idx | grep -v '|main}{1}$' | grep -v '\! =\\verb\!\*+\!\\\! +' > minitoc-fr.idx1; mv minitoc-fr.idx1 minitoc-fr.idx
sed -e's/:>/=/' < minitoc-fr.idx > minitoc-fr.idx1; mv minitoc-fr.idx1 minitoc-fr.idx
else
  echo 'French is still missing'
endif
# composition examples
#######################
foreach f ( mtc-add mtc-ads )
   foreach i ( 1 2 3 )
   pdflatex $f
   bibtex $f
      if ( -e $f.idx ) then
           makeindex -s gind.ist -o $f.ind $f.idx
      endif
      if ( -e $f.glo ) then
           makeindex -s gglo.ist -o $f.gls $f.glo
      endif
   end
end
#
foreach i ( 1 2 3 )
   foreach f ( \
            mtc-2c mtc-2nd mtc-3co  mtc-amm mtc-apx mtc-art mtc-bk mtc-bo mtc-ch0 mtc-cri \
            mtc-fko mtc-fo1 mtc-fo2 mtc-gap mtc-hi1 mtc-hi2 mtc-hia mtc-hir mtc-hop mtc-liv mtc-mem mtc-mm1 \
            mtc-mu mtc-nom mtc-ocf mtc-ofs mtc-sbf mtc-scr mtc-syn mtc-tbi mtc-tlc mtc-tlo mtc-tsf mtc-vti \
          )
      pdflatex $f
   end
   makeindex -s nomencl.ist -o mtc-nom.nls mtc-nom.nlo
end
foreach f ( mtc-add mtc-ads \
            mtc-2c mtc-2nd mtc-3co  mtc-amm mtc-apx mtc-art mtc-bk mtc-bo mtc-ch0 mtc-cri \
            mtc-fko mtc-fo1 mtc-fo2 mtc-gap mtc-hi1 mtc-hi2 mtc-hia mtc-hir mtc-hop mtc-liv mtc-mem mtc-mm1 \
            mtc-mu mtc-nom mtc-ocf mtc-ofs mtc-sbf mtc-scr mtc-syn mtc-tbi mtc-tlc mtc-tlo mtc-tsf mtc-vti \
             )
 \rm -f `cat $f.maf` $f.aux $f.log $f.toc $f.bbl $f.blg $f.lof $f.lot $f.ind $f.idx $f.ilg $f.ind $f.maf
end
\rm mtc-nom.nlo mtc-nom.nls
#######################
# repartition
echo 'Repartition of files into classes'
set WCL=/tmp/$w/CL
foreach i ( 0 1 2 3 4 5 6 7 8 9 10 )
  if ( -e ${WCL}$i ) then
    \rm -rf ${WCL}$i
  endif
  if ( -d ${WCL}$i ) then
    \rm -rf ${WCL}$i/*
    rmdir ${WCL}$i
  else
    mkdir -m 755 -p ${WCL}$i
  endif
end
# class 0
echo 'Class 0'
cp minitoc.dtx minitoc.ins minitoc-fr.dtx ${WCL}0
chmod 644 ${WCL}0/*
# class 1
echo 'Class 1'
cp minitoc.sty mtcoff.sty mtcmess.sty mtcpatchmem.sty ${WCL}1
cp *.mld *.mlo ${WCL}1
chmod 644 ${WCL}1/*
# class 2
echo 'Class 2'
cp INSTALL minitoc.l README CATALOG TODO ${WCL}2
chmod 644 ${WCL}2/*
# class 3
echo 'Class 3'
cp mtc-add.bib ${WCL}3
foreach i ( tex pdf )
   foreach j ( \
      mtc-2c mtc-2nd mtc-3co mtc-add mtc-ads mtc-amm mtc-apx mtc-art mtc-bk mtc-bo mtc-ch0 mtc-cri \
      mtc-fko mtc-fo1 mtc-fo2 mtc-gap mtc-hi1 mtc-hi2 mtc-hia mtc-hir mtc-hop mtc-liv mtc-mem mtc-mm1 \
      mtc-mu mtc-nom mtc-ocf mtc-ofs mtc-sbf mtc-scr mtc-syn mtc-tbi mtc-tlc mtc-tlo mtc-tsf mtc-vti \
   )
    cp $j.$i ${WCL}3
   end
end
chmod 644 ${WCL}3/*
# class 4
echo 'Class 4'
cp minitoc.bug minitoc.sum ${WCL}4
chmod 644 ${WCL}4/*
# class 5
echo 'Class 5'
cp minitoc.dtx minitoc.ins minitoc.bib minitoc.ist minitoc.lan en-mtc.bst ${WCL}5
chmod 644 ${WCL}5/*
# class 6
echo 'Class 6'
cp lamed3.png ${WCL}6
chmod 644 ${WCL}6/*
# class 7
echo 'Class 7'
cp minitoc.dtx minitoc-fr.dtx minitoc-fr.bib minitoc-fr.ist minitoc-fr.lan minitoc.pre ${WCL}6
cp franc.sty frbib.sty frnew.sty fr-mtc.bst ${WCL}7
chmod 644 ${WCL}7/*
# class 8
echo 'Class 8'
cp minitoc.pdf ${WCL}8
# cp minitoc.ps ${WCL}8
chmod 644 ${WCL}8/*
# class 9
echo 'Class 9'
cp minitoc-fr.pdf ${WCL}9
# cp minitoc-fr.ps ${WCL}9
chmod 644 ${WCL}9/*
# class 10
echo 'Class 10'
cp pmk imk emk fmk rmk tmk xmk cmk ${WCL}10
chmod 744 ${WCL}10/*
# Cleaning
echo "Cleaning"
if ( -f minitoc.maf ) then
   cat minitoc.maf | xargs -i -t \rm {}
endif
if ( -f minitoc-fr.maf ) then
   cat minitoc-fr.maf | xargs -i -t \rm {}
endif
#
set UN=`whoami`.tmk
set RD=/tmp/$UN
if ( -d $RD ) then
else
   mkdir -m 755 $RD
endif
set TDSDIR=tds
set TDS=$RD/$TDSDIR
echo "BIB files"
if ( -d $TDS ) then
else
   mkdir -m 755 $TDS
endif
if ( -d $TDS/bibtex ) then
else
   mkdir -m 755 $TDS/bibtex
endif
if ( -d $TDS/bibtex/bib ) then
else
   mkdir -m 755 $TDS/bibtex/bib
endif
if ( -d $TDS/bibtex/bib/minitoc ) then
   \rm -rf $TDS/bibtex/bib/minitoc
endif
mkdir -m 755 $TDS/bibtex/bib/minitoc
foreach i ( minitoc-fr.bib minitoc.bib )
   cp $i $TDS/bibtex/bib/minitoc
   chmod 744 $TDS/bibtex/bib/minitoc/$i
end
#
echo "BST files"
if ( -d $TDS/bibtex/bst ) then
else
   mkdir -m 755 $TDS/bibtex/bst
endif
if ( -d $TDS/bibtex/bst/minitoc ) then
   \rm -rf $TDS/bibtex/bst/minitoc
endif
mkdir -m 755 $TDS/bibtex/bst/minitoc
foreach i ( en-mtc.bst fr-mtc.bst)
   cp $i $TDS/bibtex/bst/minitoc
   chmod 744 $TDS/bibtex/bst/minitoc/$i
end
#
echo "SCRIPT files"
if ( -d $TDS/scripts ) then
else
   mkdir -m 755 $TDS/scripts
endif
if ( -d $TDS/scripts/minitoc ) then
   \rm -rf $TDS/scripts/minitoc
endif
mkdir -m 755 $TDS/scripts/minitoc
foreach i ( emk fmk imk pmk rmk tmk xmk cmk )
   cp $i $TDS/scripts/minitoc
   chmod 755 $TDS/scripts/minitoc/$i
end
#
echo "DVIPS files"
if ( -d $TDS/dvips ) then
else
   mkdir -m 755 $TDS/dvips
endif
if ( -d $TDS/dvips/minitoc ) then
   \rm -rf $TDS/dvips/minitoc
endif
mkdir -m 755 $TDS/dvips/minitoc
#
echo "INDEXING files"
if ( -d $TDS/makeindex ) then
else
   mkdir -m 755 $TDS/makeindex
endif
if ( -d $TDS/makeindex/minitoc ) then
   \rm -rf $TDS/makeindex/minitoc
endif
mkdir -m 755 $TDS/makeindex/minitoc
foreach i ( minitoc-fr.ist minitoc.ist )
   cp $i $TDS/makeindex/minitoc
   chmod 744 $TDS/makeindex/minitoc/$i
end
#
echo "LATEX files"
if ( -d  $TDS/tex ) then
else
   mkdir -m 755 $TDS/tex
endif
if ( -d $TDS/tex/latex ) then
else
   mkdir -m 755 $TDS/tex/latex
endif
if ( -d $TDS/tex/latex/minitoc ) then
   \rm -rf $TDS/tex/latex/minitoc
endif
mkdir -m 755 $TDS/tex/latex/minitoc
foreach i ( \
UKenglish.mld \
USenglish.mld \
acadien.mld \
afrikaans.mld \
albanian.mld \
american.mld \
arab.mld \
arab2.mld \
arabi.mld \
arabic.mld \
armenian.mld \
australian.mld \
austrian.mld \
bahasa.mld \
bahasai.mld \
bahasam.mld \
bangla.mld \
basque.mld \
bengali.mld \
bicig.mld \
bicig2.mld \
bicig3.mld \
bithe.mld \
brazil.mld \
brazilian.mld \
breton.mld \
british.mld \
bulgarian.mld \
bulgarianb.mld \
buryat.mld \
buryat2.mld \
canadian.mld \
canadien.mld \
castillan.mld \
castillian.mld \
catalan.mld \
chinese1.mld \
chinese1.mlo \
chinese2.mld \
chinese2.mlo \
croatian.mld \
czech.mld \
danish.mld \
devanagari.mld \
dutch.mld \
english.mld \
english1.mld \
english2.mld \
esperant.mld \
esperanto.mld \
estonian.mld \
ethiopia.mld \
ethiopian.mld \
ethiopian2.mld \
farsi1.mld \
farsi1.mlo \
farsi2.mld \
farsi2.mlo \
farsi3.mld \
finnish.mld \
finnish2.mld \
francais.mld \
french.mld \
french1.mld \
french2.mld \
frenchb.mld \
frenchle.mld \
frenchpro.mld \
galician.mld \
german.mld \
germanb.mld \
germanb2.mld \
greek-mono.mld \
greek-polydemo.mld \
greek-polykatha.mld \
greek.mld \
guarani.mld \
hangul-u8.mld \
hangul-u8.mlo \
hangul1.mld \
hangul1.mlo \
hangul2.mld \
hangul2.mlo \
hangul3.mld \
hangul3.mlo \
hangul4.mld \
hangul4.mlo \
hanja-u8.mld \
hanja-u8.mlo \
hanja1.mld \
hanja1.mlo \
hanja2.mld \
hanja2.mlo \
hebrew.mld \
hebrew2.mld \
hindi-modern.mld \
hindi.mld \
hungarian.mld \
icelandic.mld \
indon.mld \
indonesian.mld \
interlingua.mld \
irish.mld \
italian.mld \
italian2.mld \
japanese.mld \
japanese.mlo \
japanese2.mld \
japanese2.mlo \
japanese3.mld \
japanese3.mlo \
japanese4.mld \
japanese4.mlo \
japanese5.mld \
japanese5.mlo \
japanese6.mld \
japanese6.mlo \
kannada.mld \
khalkha.mld \
latin.mld \
latin2.mld \
latinc.mld \
latinc2.mld \
latvian.mld \
latvian2.mld \
letton.mld \
letton2.mld \
lithuanian.mld \
lithuanian2.mld \
lowersorbian.mld \
lsorbian.mld \
magyar.mld \
magyar2.mld \
magyar3.mld \
malay.mld \
malayalam-b.mld \
malayalam-keli.mld \
malayalam-keli2.mld \
malayalam-mr.mld \
malayalam-omega.mld \
malayalam-omega.mlo \
malayalam-rachana.mld \
malayalam-rachana2.mld \
malayalam-rachana3.mld \
manju.mld \
mexican.mld \
meyalu.mld \
minitoc.sty \
mongol.mld \
mongolb.mld \
mongolian.mld \
mtcmess.sty \
mtcoff.sty \
mtcpatchmem.sty \
naustrian.mld \
newzealand.mld \
ngerman.mld \
ngermanb.mld \
ngermanb2.mld \
norsk.mld \
norsk2.mld \
nynorsk.mld \
nynorsk2.mld \
occitan.mld \
occitan2.mld \
polish.mld \
polish2.mld \
polski.mld \
portuges.mld \
portuguese.mld \
romanian.mld \
romanian2.mld \
romanian3.mld \
russian-cca.mld \
russian-cca.mlo \
russian-cca1.mld \
russian-cca1.mlo \
russian-lh.mld \
russian-lh.mlo \
russian-lhcyralt.mld \
russian-lhcyralt.mlo \
russian-lhcyrkoi.mld \
russian-lhcyrkoi.mlo \
russian-lhcyrwin.mld \
russian-lhcyrwin.mlo \
russian.mld \
russian2m.mld \
russian2o.mld \
russianb.mld \
russianc.mld \
samin.mld \
scottish.mld \
serbian.mld \
serbianc.mld \
slovak.mld \
slovene.mld \
spanish.mld \
spanish2.mld \
spanish3.mld \
spanish4.mld \
swahili.mld \
swedish.mld \
swedish2.mld \
thai.mld \
thai.mlo \
turkish.mld \
uighur.mld \
uighur2.mld \
uighur3.mld \
ukraineb.mld \
ukrainian.mld \
uppersorbian.mld \
usorbian.mld \
vietnam.mld \
vietnamese.mld \
welsh.mld \
xalx.mld \
xalx2.mld \
xalx3.mld \
)
   cp $i $TDS/tex/latex/minitoc
   chmod 744 $TDS/tex/latex/minitoc/$i
end
#
## echo "TPM file"
## if ( -d $TDS/tpm ) then
## else
##    mkdir -m 755 $TDS/tpm
## endif
## cp minitoc.tpm $TDS/tpm/minitoc.tpm
## chmod 744 $TDS/tpm/minitoc.tpm
#
echo "DOCUMENTATION files"
if ( -d $TDS/doc ) then
else
   mkdir -m 755 $TDS/doc
endif
if ( -d $TDS/doc/latex ) then
else
   mkdir -m 755 $TDS/doc/latex
endif
if ( -d $TDS/doc/latex/minitoc ) then
   \rm -rf $TDS/doc/latex/minitoc
endif
mkdir -m 755 $TDS/doc/latex/minitoc
foreach i ( \
INSTALL \
README \
TODO \
CATALOG \
minitoc-fr.lan \
minitoc-fr.pdf \
minitoc.bug \
minitoc.l \
minitoc.lan \
minitoc.pdf \
minitoc.pre \
minitoc.sum \
franc.sty \
frbib.sty \
frnew.sty \
)
   cp $i $TDS/doc/latex/minitoc
end
echo "EXAMPLE files"
mkdir -m 755 $TDS/bibtex/bib/minitoc/examples
foreach i ( \
mtc-2c.pdf \
mtc-2c.tex \
mtc-2nd.pdf \
mtc-2nd.tex \
mtc-3co.pdf \
mtc-3co.tex \
mtc-add.pdf \
mtc-add.tex \
mtc-add.bib \
mtc-ads.pdf \
mtc-ads.tex \
mtc-amm.pdf \
mtc-amm.tex \
mtc-apx.pdf \
mtc-apx.tex \
mtc-art.pdf \
mtc-art.tex \
mtc-bk.pdf \
mtc-bk.tex \
mtc-bo.pdf \
mtc-bo.tex \
mtc-ch0.pdf \
mtc-ch0.tex \
mtc-cri.pdf \
mtc-cri.tex \
mtc-fko.pdf \
mtc-fko.tex \
mtc-fo1.pdf \
mtc-fo1.tex \
mtc-fo2.pdf \
mtc-fo2.tex \
mtc-gap.pdf \
mtc-gap.tex \
mtc-hi1.pdf \
mtc-hi1.tex \
mtc-hi2.pdf \
mtc-hi2.tex \
mtc-hia.pdf \
mtc-hia.tex \
mtc-hir.pdf \
mtc-hir.tex \
mtc-hop.pdf \
mtc-hop.tex \
mtc-liv.pdf \
mtc-liv.tex \
mtc-mem.pdf \
mtc-mem.tex \
mtc-mm1.pdf \
mtc-mm1.tex \
mtc-mu.pdf \
mtc-mu.tex \
mtc-nom.pdf \
mtc-nom.tex \
mtc-ocf.pdf \
mtc-ocf.tex \
mtc-ofs.pdf \
mtc-ofs.tex \
mtc-sbf.pdf \
mtc-sbf.tex \
mtc-scr.pdf \
mtc-scr.tex \
mtc-syn.pdf \
mtc-syn.tex \
mtc-tbi.pdf \
mtc-tbi.tex \
mtc-tlc.pdf \
mtc-tlc.tex \
mtc-tsf.pdf \
mtc-tsf.tex \
mtc-vti.pdf \
mtc-vti.tex \
)
   cp $i $TDS/doc/latex/minitoc/examples
end
echo "IMAGE files"
mkdir -m 755 $TDS/bibtex/bib/minitoc/images
foreach i ( \
lamed3.png \
)
   cp $i $TDS/doc/latex/minitoc/images
   chmod 644 $TDS/doc/latex/minitoc/images/$i
end
#
echo "SOURCE files"
if ( -d $TDS/source ) then
else
   mkdir -m 755 $TDS/source
endif
if ( -d $TDS/source/latex ) then
else
   mkdir -m 755 $TDS/source/latex
endif
if ( -d $TDS/source/latex/minitoc ) then
   \rm -rf $TDS/source/latex/minitoc
endif
mkdir -m 755 $TDS/source/latex/minitoc
foreach i ( minitoc-fr.dtx minitoc.dtx minitoc.ins )
   cp $i $TDS/source/latex/minitoc
   chmod 744 $TDS/source/latex/minitoc/$i
end
#
echo "MINITOC-TDS.ZIP"
set WD=`pwd`
cd $RD/$TDSDIR
\rm -f minitoc-tds.zip
\rm -f minitoc.tds.zip
zip -r minitoc.tds.zip * -i \*
cd $WD
# it's all!
echo "It's all, folks..."
exit

